spring:
  datasource:
    #url: jdbc:mysql://bbf2z0kunelo93cmfu1l-mysql.services.clever-cloud.com:3306/bbf2z0kunelo93cmfu1l?serverTimezone=UTC&useSSL=true&requireSSL=false
    #username: uimnsbblk9y4wktt
    #password: 6UyOHjDtYUHyvxky0vJa

    url: jdbc:mysql://localhost:3306/deporteonline?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

