#
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/deportesunla?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/deporteonline?serverTimezone=UTC
    username: root
    #password: Yagami40811091
    password: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
apiKey:
  #sendGrid: SG.lvjF-kXyTvKW9BVU5-BWTg.(ESTO SE TIENE QUE BORRAR, SOLO EL CONTENIDO EN PARENTESIS.)NoakW6UfxUejfCT4adbpv6YYrFY95scciUaJQtUuwAI
  sendGrid: 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

