spring:
  datasource:
    url: jdbc:mysql://trinidadmysql.mysql.database.azure.com:3306/deporteonline?serverTimezone=UTC&useSSL=true&requireSSL=false
    username: juantrinidad@trinidadmysql
    password: unla.1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

