#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deporteonline?serverTimezone=UTC
    username: tuuser
    password: tupassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
apiKey:
  sendGrid: 

