#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deporteonline?serverTimezone=UTC
    username: root
    password: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
apiKey:
  sendGrid: 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

