spring:
  datasource:
    url: jdbc:mysql://trinidadmysql.mysql.database.azure.com:3306/deporteonline?useSSL=true&requireSSL=false
    username: root
    password: Yagami40811091
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

