# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - deportesunla

on:
  push:
    branches:
      - spring-security\Grupo-4-PS-2020\API\*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deportesunla'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d576501373074e9aad9970140d8a1afe }}
        package: '${{ github.workspace }}/target/*.jar'
